package com.model;

import javax.swing.JLabel;
import javax.swing.JTable;

/**
 * Cette classe permet l'affichage de la liste des clients ou des prospect.
 *
 * @author Maxime
 */
public class AffichageListeFrame extends javax.swing.JFrame {

    // ControleurFrame des Frames
    private ControleurFrame controleur;

    /**
     * Constructeur implicite.
     */
    public AffichageListeFrame() {
        initComponents();
        
    }

    /**
     * Modifie le controleur
     *
     * @param controleur de type ControleurFrame.
     */
    public void setControleur(ControleurFrame controleur) {
        this.controleur = controleur;
    }

    public JLabel getjLabelTitreTableau() {
        return jLabelTitreTableau;
    }

    public void setjLabelTitreTableau(JLabel jLabelTitreTableau) {
        this.jLabelTitreTableau = jLabelTitreTableau;
    }

    public JTable getjTableAffichage() {
        return panTbAffichageListe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "Convert2Lambda"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTableauAffichage = new javax.swing.JPanel();
        jLabelTitreTableau = new javax.swing.JLabel();
        panFooterAffichageListe = new javax.swing.JPanel();
        bpMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panTbAffichageListe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("affichageFrame");
        setResizable(false);

        jLabelTitreTableau.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitreTableau.setText("Titre du Tableau");

        javax.swing.GroupLayout jPanelTableauAffichageLayout = new javax.swing.GroupLayout(jPanelTableauAffichage);
        jPanelTableauAffichage.setLayout(jPanelTableauAffichageLayout);
        jPanelTableauAffichageLayout.setHorizontalGroup(
            jPanelTableauAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableauAffichageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreTableau, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTableauAffichageLayout.setVerticalGroup(
            jPanelTableauAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableauAffichageLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitreTableau, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        bpMenu.setText("Menu");
        bpMenu.setPreferredSize(new java.awt.Dimension(80, 32));
        bpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpMenuActionPerformed(evt);
            }
        });

        jButton1.setText("Quitter");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 32));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFooterAffichageListeLayout = new javax.swing.GroupLayout(panFooterAffichageListe);
        panFooterAffichageListe.setLayout(panFooterAffichageListeLayout);
        panFooterAffichageListeLayout.setHorizontalGroup(
            panFooterAffichageListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFooterAffichageListeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panFooterAffichageListeLayout.setVerticalGroup(
            panFooterAffichageListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFooterAffichageListeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFooterAffichageListeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panTbAffichageListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        panTbAffichageListe.setPreferredSize(new java.awt.Dimension(1920, 750));
        jScrollPane1.setViewportView(panTbAffichageListe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(jPanelTableauAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 752, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panFooterAffichageListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTableauAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panFooterAffichageListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bouton menu, pour revenir au menu du programme.
     *
     * @param evt du type ActionEvent
     */
    private void bpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpMenuActionPerformed
        controleur.menuEvent(evt);
    }//GEN-LAST:event_bpMenuActionPerformed
    /**
     * Bouton quitter, fait quitter le programme.
     *
     * @param evt du type ActionEvent
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controleur.quitterEvent(evt);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelTitreTableau;
    private javax.swing.JPanel jPanelTableauAffichage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panFooterAffichageListe;
    private javax.swing.JTable panTbAffichageListe;
    // End of variables declaration//GEN-END:variables
}
